# Generated by Django 6.0.6 on 2026-06-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_marcacion_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcacion',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('SALIDA_DESCANSO', 'Salida Descanso'), ('ENTRADA_DESCANSO', 'Entrada Descanso'), ('ENTRADA_TE', 'Entrada T.E.'), ('SALIDA_TE', 'Salida T.E.')], max_length=30),
        ),
    ]
